### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by blinditachi** [monosans/proxy-scraper-checker#12]
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 462, in get_loader
    return find_loader(fullname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 472, in find_loader
    for importer in iter_importers(fullname):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 428, in iter_importers
    __import__(pkg)
  File "main.py", line 27
    def __init__(self, socket_address: str, ip: str) -> None:
                                     ^
SyntaxError: invalid syntax

**Comment by monosans** [comment]
Hi!

Python 2.7 is unsupported. Please use Python 3.7 or higher.
