### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Roboxkin** [monosans/proxy-scraper-checker#36]
F:\proxy>python main.py
https://api.proxyscrape.com/v2/?request=getproxies&protocol=http | No proxies found | Status code 403
https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4 | No proxies found | Status code 403
https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5 | No proxies found | Status code 403
https://raw.githubusercontent.com/hanwayTech/free-proxy-list/main/socks5.txt | No proxies found
https://raw.githubusercontent.com/hanwayTech/free-proxy-list/main/socks4.txt | No proxies found
https://proxysearcher.sourceforge.net/Proxy%20List.php?type=socks | No proxies found
https://raw.githubusercontent.com/hanwayTech/free-proxy-list/main/https.txt | No proxies found
https://raw.githubusercontent.com/hanwayTech/free-proxy-list/main/http.txt | No proxies found
https://proxysearcher.sourceforge.net/Proxy%20List.php?type=socks | No proxies found
Traceback (most recent call last):
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in
run_until_complete
    self.run_forever()
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in
run_forever
    self._run_once()
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1845, in
_run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\proxy\main.py", line 403, in <module>
    asyncio.run(main())
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 63, in
_cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in
run_until_complete
    self.run_forever()
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in
run_forever
    self._run_once()
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1845, in
_run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()
Scraper :: HTTP   ---------------------------------------- 100% 42/42
Scraper :: SOCKS4 ---------------------------------------- 100% 21/21
Scraper :: SOCKS5 ---------------------------------------- 100% 23/23
Checker :: HTTP   ----------------------------------------   0%     0/21368
Checker :: SOCKS4 ----------------------------------------   0%    0/7759
Checker :: SOCKS5 ----------------------------------------   0%    0/4395  Exception ignored in: <coroutine object main at 0x0000020784BB02E0>
Traceback (most recent call last):
  File "F:\proxy\main.py", line 369, in main
  File "F:\proxy\main.py", line 316, in main
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\progress.py", line 1178, in __exit__
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\progress.py", line 1164, in stop
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\live.py", line 147, in stop
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 869, in __exit__
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 827, in _exit_buffer
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 2017, in _check_buffer
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <coroutine object Proxy.check at 0x0000020784BB3BC0>
Traceback (most recent call last):
  File "F:\proxy\main.py", line 242, in check_proxy
RuntimeError: coroutine ignored GeneratorExit
Exception ignored in: <coroutine object Proxy.check at 0x0000020784CE8350>
Traceback (most recent call last):

**Comment by monosans** [comment]
Reinstall the latest version of Python and dependencies. This should help.
