### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by chekamarue** [monosans/proxy-scraper-checker#4]
getting tis error 

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\CRACKEN\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\CRACKEN\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in
_call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

ten script rescan again

**Comment by monosans** [comment]
Try setting `MAX_CONNECTIONS` to lower value. 

I'd suggest decreasing it by 50 until you get rid of the error.
