### ISSUE TITLE
i get error and its crashing

### ISSUE THREAD

**Issue by 9dl** [monosans/proxy-scraper-checker#8]
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in
_call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen

**Comment by monosans** [comment]
Hi!

Try setting lower `MAX_CONNECTIONS` value.

**Comment by 9dl** [comment]
still errors coming its works but its coming these errors
